object FrmSingleChat: TFrmSingleChat
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = 'Single Chat'
  ClientHeight = 416
  ClientWidth = 587
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 587
    Height = 80
    Align = alTop
    Caption = 'CHAT'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    object LbApelido: TLabel
      Left = 67
      Top = 30
      Width = 65
      Height = 19
      Caption = 'An'#244'nimo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object LbStatus: TLabel
      Left = 503
      Top = 32
      Width = 60
      Height = 19
      Caption = 'STATUS'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsItalic]
      ParentFont = False
    end
    object LbApelidoRecipiente: TLabel
      Left = 67
      Top = 55
      Width = 65
      Height = 19
      Caption = 'An'#244'nimo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label2: TLabel
      Left = 14
      Top = 32
      Width = 26
      Height = 19
      Caption = 'DE:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 14
      Top = 55
      Width = 47
      Height = 19
      Caption = 'PARA:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 376
    Width = 587
    Height = 40
    Align = alBottom
    TabOrder = 1
    object BtnChatClear: TButton
      Left = 521
      Top = 5
      Width = 58
      Height = 31
      Caption = 'LIMPAR'
      TabOrder = 0
      OnClick = BtnChatClearClick
    end
    object BtnChatOk: TButton
      Left = 457
      Top = 5
      Width = 58
      Height = 31
      Caption = 'ENVIAR'
      TabOrder = 1
      OnClick = BtnChatOkClick
    end
    object EdTexto: TEdit
      Left = 24
      Top = 5
      Width = 427
      Height = 31
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      TextHint = 'digite aqui...'
      OnKeyPress = EdTextoKeyPress
    end
  end
  object Panel5: TPanel
    Left = 0
    Top = 80
    Width = 587
    Height = 296
    Align = alClient
    TabOrder = 2
    object MChatConteudo: TMemo
      Left = 1
      Top = 1
      Width = 585
      Height = 294
      Align = alClient
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
  end
  object Timer1: TTimer
    Enabled = False
    Interval = 2000
    OnTimer = Timer1Timer
    Left = 424
    Top = 16
  end
end
